### ISSUE TITLE
How to change the foreground in RightWindowCommands?

### ISSUE THREAD

**Issue by arnezami** [MahApps/MahApps.Metro#2052]
Hello everyone!

Thanks for your library, I realy like it.

I have a issue about the RightWindowCommands: I can't to change the fore color on the buttons.
The version of MahApps.Metro: 0.13.1.0

This code doesn't work:

```XAML
<ERIEntities:BaseMetroWindow.RightWindowCommands>
        <Controls:WindowCommands Foreground="White">
            <Button Foreground="White" x:Name="tsbtnAbout" Click="tsbtnAbout_Click"
                    ToolTip="{tsl:Translate sysGoToAboutPage}"
                    Content="{tsl:Translate tsbAbout}" >
            </Button>
            <Button Foreground="White" x:Name="tsbSettingPage" Click="btnSettingsPage_Click"
                    ToolTip="{tsl:Translate sysGoToSettingPage}"
                    Content="{tsl:Translate tsbSettingPage}" />
			<Image x:Name="imgLanguage" Source="Images/Languages/32/en-us.png" Width="20" Margin="5,2,5,0" HorizontalAlignment="Left" Grid.Row="1" Height="20" />
        </Controls:WindowCommands>
    </ERIEntities:BaseMetroWindow.RightWindowCommands>
```

Any ideas?

![image](https://cloud.githubusercontent.com/assets/3115768/8850796/9f125222-3153-11e5-98c4-70c3a078fca2.png)

**Comment by crumbl3d** [comment]
I can confirm this. Having the same bug (you can see it on Gitter). I tried everything but nothing works. I will try to edit this in MetroWindow.xaml itself but I don't think it will work.

**Comment by arnezami** [comment]
I updated the version of library to version 1.1.3.0 and problem is fixed. Thanks a lot.

**Comment by crumbl3d** [comment]
@arnezami I updated as well but it isn't fixed for me. Can you please explain how you made it work?
