### ISSUE TITLE
Expander Style - Toggle Icon colour

### ISSUE THREAD

**Issue by chri55w** [MahApps/MahApps.Metro#2200]
I'm currently using Version 1.1.2 so forgive me if this has since been fixed but I haven't found any reference to it.

The Icon for the expander (Ellipse and Arrow) appear to be bound to the foreground colour rather than the IdealForegroundColour. This causes some inconsistency when using the Lime, Pink and Amber themes show the Icon in Black while the IdealForegroundColour is White.

**Comment by dsaf** [comment]
I have noticed some weirdness either - the color of the header text doesn't match the color of the button when changing the background color.

**Comment by chri55w** [comment]
From what I've seen the Header's Text colour does match the colour of the button however neither match the colour of the writing in the titlebar etc. I dont know if this is related to the changes made for #1748 but seems possible?

**Comment by punker76** [comment]
@chri55w @dsaf this should be already fixed in the alphs version!

![2015-11-06_15h38_53](https://cloud.githubusercontent.com/assets/658431/10999508/ad8f69d8-849c-11e5-9677-8e6e3d283101.png)
![2015-11-06_15h39_18](https://cloud.githubusercontent.com/assets/658431/10999512/b36ea526-849c-11e5-9a0f-1a64ad1b130d.png)
![2015-11-06_15h39_27](https://cloud.githubusercontent.com/assets/658431/10999514/b721c824-849c-11e5-80d7-b08db36ed1eb.png)

**Comment by dsaf** [comment]
@punker76 can't wait for release :). BTW what is the best way to get a nice dictionary of "Metro" colors? System colors are not ideal.

**Comment by chri55w** [comment]
So I've upgraded to 1.1.3-ALPHA225 via NuGet and im still seeing the same issue 
![image](https://cloud.githubusercontent.com/assets/10941226/10999913/a1a42178-8496-11e5-9a82-4458b2cdc34d.png)

As you can tell the Header Template is changed so it is irrelevant. However you can see the colour of the expander icon is different to the colour of the window title?

**Comment by dsaf** [comment]
@chri55w if you want a quick fix:

```xaml
<Expander.Header>
<Grid >
<TextBlock Foreground="{Binding Background, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=Expander}, Converter={x:Static Converters:BackgroundToForegroundConverter.Instance}}">
...
```

**Comment by punker76** [comment]
Ok, that's right, `Expander` and `GroupBox` doesn't use the `IdealForegroundColorBrush`, `MetroWindow`does. So you can do it by

```xaml
<Expander Controls:GroupBoxHelper.HeaderForeground="{DynamicResource IdealForegroundColorBrush}" />
```

**Comment by chri55w** [comment]
@punker76 Ah, Yes that worked, Thank you!
