### ISSUE TITLE
IgnoreTaskbarOnMaximize stopped working after windows 10 anniversary update.

### ISSUE THREAD

**Issue by igorushi** [MahApps/MahApps.Metro#2618]
## What steps will reproduce this issue?

Update windows 10 to version 1607, build 14393.51
set `IgnoreTaskbarOnMaximize=true`
Mahapps window **doesn't** overlaps the taskbar.
### Expected outcome

Application Window overlaps the taskbar. 
## 
### Environment
- MahApps.Metro **v1.3.0-ALPHA147**
- Windows **Windows 10  (version 1607, build 14393.51)**
- Visual Studio **2015.3**
- .NET Framework **4.6**

**Comment by punker76** [comment]
@igorushi :-( Another taskbar change by Microsoft... Don't know what is changed, hopefully it's easy to fix.

**Comment by punker76** [comment]
@igorushi It seems like w are not alone... http://eu.battle.net/forums/en/wow/topic/17612914040

**Comment by shanselman** [comment]
Checking

**Comment by MurariAlex** [comment]
_Apparently_ there's an Windows Update that address this issue.

http://www.tenforums.com/general-support/61190-how-do-i-disable-always-top-taskbar.html

**Comment by igorushi** [comment]
@MurariAlex Unfortunately on my PC it still doesn't works even after latest updates.
There is a pull request with a work around that works for me: #2620

**Comment by punker76** [comment]
@igorushi Thx again for this hack. I leave this issue open, cause I think this is not a bug by MahApps. I changed a little bit the hack, so it will only be done under Win10 fe7dd828dbc945a705f10be67983a75a147328fc. There was also a bug if the flag was unset while the window is still maximized.

**Comment by punker76** [comment]
@igorushi MahApps.Metro 1.3.0-ALPHA190 contains the fix

**Comment by igorushi** [comment]
@punker76 great, thanks.

**Comment by adeniltonbs** [comment]
In MahApps 1.4.0-ALPHA 003, when I set up the main window as IgnoreTaskbarOnMaximize = "True", the window always on top, preventing other windows to appear in front of her, even if the application is restored.
The window stops stay on top when the application is minimized and restored. But then the task bar is in front again.

I used the sample https://github.com/punker76/code-samples/tree/master/MahAppsMetroFullScreen to reproduce the problem.

Here a gif with first problem reported.
![mahapp](https://cloud.githubusercontent.com/assets/6733483/19004972/b2f7583c-872e-11e6-9867-8b78f0458a22.gif)

**Comment by punker76** [comment]
@adeniltonbs I think I know what it is, I'll try to fix this...

**Comment by adeniltonbs** [comment]
👍

**Comment by t0lik** [comment]
@punker76 Please, pay attention to [https://github.com/mike-ward/Markdown-Edit/issues/196#issuecomment-250997154](url)

**Comment by xmedeko** [comment]
Is this bug still valid? Cannot reproduce it with the latest Markdown-Edit and Win10 1703.

**Comment by igorushi** [comment]
@xmedeko , a problem described by @adeniltonbs in 1703 is still there since the "fix" was to push window in front of taskbar ... so far a best approach is 'don't hold it that way'

**Comment by xmedeko** [comment]
Sill cannot reproduce it, even with MahAppsMetroFullScreen. I have remove all the code from MahAppsMetroFullScreen, I do not change `UseNoneWindowStyle` to have window chrome visible always. The taskbar is always hidden when the window is in the maximized state, even if I mimize it and then restore it.

**Comment by igorushi** [comment]
The initial issue is fixed.

**Comment by xmedeko** [comment]
Well, I got a rare use case, when the taskbar appears. The taskbar autohiding is **off**. Chage Windows DPI (Settings -> Change the size of text, apps, and other items) to 125%. Open some apps to have icons on the toolbar. Open the `MahAppsMetroFullScreen` then go with a mouse to the last bottom (or where the toolbar is) pixel line of the screen, to the (horizontal) position, where the apps icons were before they were hidden by the `MahAppsMetroFullScreen`. The app preview window tries to popup and it shows the toolbar.
Should this issue be reopened or should I report another issue?

**Comment by punker76** [comment]
@xmedeko I can't reproduce this with the latest pre-release of MahApps (I just updated the code samples).

**Comment by xmedeko** [comment]
Still happening with the `1.6.0-alpha0176`. Also, I have 1680x1050 screen. When you change the DPI, then you may have just a few icons left on the taskbar, since they are in "pages". So, you have to move your mouse on the bottom left part. Also, it does not happen in the space among the icons. So I move a bit and wait, then move i bit and wait, ... all in the last bottom line.

**Comment by punker76** [comment]
@xmedeko I don't get it. Is your Taskbar auto-hidden or fixed? Can you create a screencast?

**Comment by xmedeko** [comment]
The taskbar autohiding is **off**.  Fixed on or off, does not matter. DPI 125%.

Screencast is simple, I have a the taskbar on the right, (but the same problem is when I move it down,) see https://www.dropbox.com/s/r91wyz0n9wvot4i/MahApps2681.mp4 I've just moved a mouse a bit on the most right position, and the preview windows have poped up. The taskbar pops up the taskbar sometimes too, and then the taskbar stays there even if I move the mouse away. And that's the main problem for our app. (Reported from 3 other users.) I was not able to make to taskbar appear when making screencast, just the preview windows (maybe the screencast app ShareX influence?).

But, if I make autohiding **on**, then the problem is more easily to simulate. With DPI 100% the taskbar does not appear. With DPI 125% the taskbar appears immediatelly when I move the mouse to the right, but autohides when I move the mouse away.
