### ISSUE TITLE
Mahapps UI is locked in Dialog Window after re-login

### ISSUE THREAD

**Issue by kopacz0** [MahApps/MahApps.Metro#2734]
Mahapps UI in Dialog Window is locked when user  re-signs in.
### **Steps to Reproduce**
In order to reproduce please use the below sample app:
- Open Dialog Window from the Main window by clicking "Display Window" button
- The dialog window is displayed
- Lock out using Windows+L button
- Login again
- Try to enter any text to textbox

Per the attached example. User is not able to enter any text to the textbox. Generally UI is locked. User is able to switch to the second tab, but is not able to return to first tab.

### **Expected outcome**
The textbox and whole UI should not be locked to allow user to use it.

### **Environment:**
- MahApps.Metro 1.3.0 stable
- Visual Studio 2015 Community
- .NET Framework 4.6.1

### **Demo App**
[SampleMahapps.zip](https://github.com/MahApps/MahApps.Metro/files/569690/SampleMahapps.zip)

**Comment by cavando** [comment]
I am having the same issues, has this been looked at yet?

**Environment:**

- MahApps.Metro 1.3.0 stable

- Visual Studio 2013 Professional

- .NET Framework 4.0

**Comment by fussmonkey** [comment]
We see the same issue, if the window is visible when locking the workstation and logging back in, the UI is unresponsive. If I close the window and re-open it, the entire UI is actually transparent, except for the border. 

I can fix the issue by minimizing all windows on my workstation (Win+D). At that point, if I open the windwo again the UI seems back to normal (until the next time I lock the machine).

- MahApps.Metro 1.3.0 stable

- Visual Studio 2015 Enterprise

- .NET Framework 4.5.2

**Comment by gkinsman** [comment]
#2742 is a duplicate of this and an issue I'm seeing too 😃.

To add some more information:

- I've found that width doesn't trigger this bug, but height does. Keeping the window height below ~350px fixes the problem, and makes controls visible/usable again. 
- Large memory spikes can occur after some time when the window remains active. The memory doesn't seem to be used by the process itself, but on some system thread, perhaps GC.
- Attaching more monitors/removing monitors appears to fix the issue until next sleep/login.

Cheers

**Comment by gkinsman** [comment]
http://discussions.citrix.com/topic/280158-wpf-rendering-issue-after-unlocking-computer/

**Comment by gkinsman** [comment]
I've found a workaround for this:

```
window.Loaded += (s, e) =>
{
    var w = (Window) s;
    var src = PresentationSource.FromVisual(w) as HwndSource;
    var target = src.CompositionTarget;
    target.RenderMode = RenderMode.SoftwareOnly;
};
```

It appears to be some kind of driver issue in windows that's causing hardware rendering to fail when the shell environment is restored. Forcing software rendering for that window solves the issue for me.

**Comment by punker76** [comment]
@kopacz0 
@cavando 
@fussmonkey 
@gkinsman 

I think I fixed this with cafa38c9c4aac459e505ffe25987375ba1c09336
Please test and try latest pre-release 1.4.0-ALPHA029
Thx!

**Comment by LuisHCK** [comment]
I'm upgrade the nuget package to **1.4.0-ALPHA035** and I still have the same bug when re-login.

**Environment:**
- MahApps.Metro 1.4.0-ALPHA035
- VS Comunity
- .NET Framework 4.5.2
![version](https://cloud.githubusercontent.com/assets/5175137/20863719/c57f5886-b999-11e6-89b1-3c3eaa6b8760.png)
_Note: I tried to resize the window. This is the result_

**Comment by LuisHCK** [comment]
@gkinsman sorry for the noob question, but where i put this?
```
window.Loaded += (s, e) =>
{
    var w = (Window) s;
    var src = PresentationSource.FromVisual(w) as HwndSource;
    var target = src.CompositionTarget;
    target.RenderMode = RenderMode.SoftwareOnly;
};
```
thank you

**Comment by punker76** [comment]
@LuisHCK it looks like you don't use the MetroWindow...

**Comment by gkinsman** [comment]
Ah, @LuisHCK I'm using it with Caliburn, so I have a window manager. If you use plain mahapps you'll obviously need to override the loaded event in your MetroWindow as you have :)
