### ISSUE TITLE
Command binding not working on FlipView next item

### ISSUE THREAD

**Issue by jfquarto** [MahApps/MahApps.Metro#3375]
My FlipView in Xaml:
```
<Controls:FlipView ItemsSource="{Binding MyTabs}" CircularNavigation="True" SelectedIndex="0">
	<Controls:FlipView.ItemTemplate>
		<DataTemplate>
			<ContentControl HorizontalAlignment="Center" VerticalAlignment="Center" Content="{Binding Buttons}" />
		 </DataTemplate>
	</Controls:FlipView.ItemTemplate>
</Controls:FlipView>

```
MyTabs is an ObservableCollection of class Tab.
Class Tab has a property Buttons which is a Grid with Button controls on it.
Each button has a Command binding (MyTabs is created in the viewmodel constructor):
```
button.SetBinding(Button.CommandProperty, new Binding("DataContext.ButtonCommand") { RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(FlipView),1) });
button.CommandParameter = id.ToString();

```
Now all works fine on the first FlipView item selected via SelectedIndex. If I click on a button the Command is executed. But when I navigate to next item the command binding of the buttons on that item don't work. Same goes for the next items. Only the buttons on the initial selected item will work ok. For example if I change the value of SelectedIndex in the Xaml to 2, then only the buttons on item 2 work ok.

**Comment by jfquarto** [comment]
Do you need more information ?

**Comment by punker76** [comment]
@jfquarto Which MahApps version are you using?

**Comment by punker76** [comment]
@jfquarto I think this is fixed in the current dev branch b83db30511fed40eda672c0e302abc8f92348d39

**Comment by jfquarto** [comment]
Build MahApps from the current dev branch and used it in my project.
But it didn't solve my problem.

**Comment by punker76** [comment]
@jfquarto It would be nice if you can create a short sample and separate this.

**Comment by jfquarto** [comment]
Here's the sample;
[FlipViewTest.zip](https://github.com/MahApps/MahApps.Metro/files/2680002/FlipViewTest.zip)

**Comment by punker76** [comment]
@jfquarto The problem here is, that you are mixing MVVm with creating visuals in code behind. It works for the first tab, because there is a existing visual tree and for the other tabs it doesn't exists. In your case you can do this at the KeyboardCreator:

```
...

//
//the command binding
//
button.CommandParameter = id.ToString();
grid2.Children.Add(button);
grid2.Loaded += (sender, args) =>
{
    BindingOperations.ClearBinding(button,Button.CommandProperty);
    button.SetBinding(Button.CommandProperty, new Binding("DataContext.KeyCommand") {RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(FlipView), 1)});
};

...
```
